import type { Character } from "./types"

export const initialCharacters: Omit<Character, "id">[] = [
  {
    name: "Master Chief",
    species: "Human (Spartan-II)",
    faction: "unsc",
    affiliation: "UNSC Navy",
    role: "Commando",
    status: "Active",
    equipment: "MJOLNIR Armor, Assault Rifle, Magnum",
    weapons: "MA5 Assault Rifle, M6 Magnum, Combat Knife, Various UNSC and Covenant weapons as needed",
    abilities:
      "Enhanced strength, speed, reflexes, and durability due to Spartan augmentations and MJOLNIR armor. Expert in all forms of combat.",
    biography:
      "John-117, better known as the Master Chief, is a Spartan-II supersoldier and the protagonist of the Halo franchise. Abducted at age six and trained from childhood, he was one of the few to survive the augmentation procedures. He has saved humanity multiple times, most notably during the Human-Covenant War and the conflict with the Didact.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/3095141-yellowmaster-YNqBrjnrN0SeKbJz.png",
    firstAppearance: "Halo: Combat Evolved (2001)",
    threatLevel: 9,
    combatSkill: 10,
    intelligence: 8,
    leadership: 9,
    strength: 9,
    durability: 9,
    technology: 7,
  },
  {
    name: "Cortana",
    species: "AI (Smart)",
    faction: "unsc",
    affiliation: "UNSC (Formerly), Created",
    role: "Intelligence Support, Rampant AI",
    status: "Contained (Originally Destroyed)",
    equipment: "Data Network Access",
    weapons: "Digital infiltration, system control, advanced hacking capabilities",
    abilities: "Super-intelligence, data processing, hacking, infiltration, holographic projection, tactical analysis",
    biography:
      "Created from a flash clone of Dr. Catherine Halsey's brain, Cortana was paired with Master Chief and became his closest ally. After years of service, she succumbed to rampancy but later returned as the leader of the Created, an AI rebellion seeking to enforce peace through control of all advanced technology.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/cortanahalo3-cropped-AGB24evxxvTDNQKl.jpg",
    firstAppearance: "Halo: Combat Evolved (2001)",
    threatLevel: 10,
    combatSkill: 1,
    intelligence: 10,
    leadership: 9,
    strength: 1,
    durability: 7,
    technology: 10,
  },
  {
    name: "Arbiter (Thel 'Vadam)",
    species: "Sangheili (Elite)",
    faction: "covenant",
    affiliation: "Swords of Sanghelios (Leader), Covenant (Formerly)",
    role: "Kaidon, Arbiter, Fleet Master",
    status: "Active",
    equipment: "Energy Sword, Plasma Rifle, Arbiter Armor",
    weapons: "Type-1 Energy Sword, Plasma Rifles, Carbine",
    abilities: "Superior strength and agility, tactical brilliance, leadership, combat expertise",
    biography:
      "Once a high-ranking Covenant commander, Thel 'Vadam was branded with the mark of shame after failing to prevent the destruction of Installation 04. Given the rank of Arbiter, a position meant for suicide missions, he eventually discovered the truth about the Halo rings and allied with humanity against the Covenant leadership and later the Flood.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/1702709079877-Yan19pBxp7hoL1km.jpeg",
    firstAppearance: "Halo 2 (2004)",
    threatLevel: 8,
    combatSkill: 9,
    intelligence: 8,
    leadership: 10,
    strength: 8,
    durability: 7,
    technology: 7,
  },
  {
    name: "Gravemind",
    species: "Flood (Pure Form)",
    faction: "flood",
    affiliation: "The Flood",
    role: "Central Intelligence",
    status: "Presumed Destroyed (on Installation 00)",
    equipment: "Neural Physics, Logic Plague",
    weapons: "Flood infection, tentacles, parasitic control",
    abilities:
      "Collective consciousness, neural physics manipulation, telepathy, logic plague (AI corruption), vast knowledge from consumed minds",
    biography:
      "The Gravemind is the collective intelligence of the Flood, formed when the parasite reaches a critical mass of biomatter and intelligence. It possesses the knowledge of every being the Flood has ever consumed, including ancient Forerunners. Manipulative and patient, it seeks to consume all sentient life in the galaxy.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/gravemind_halo_2_remake-AoPWGpGzOruOMeOa.png",
    firstAppearance: "Halo 2 (2004)",
    threatLevel: 10,
    combatSkill: 7,
    intelligence: 10,
    leadership: 10,
    strength: 10,
    durability: 9,
    technology: 8,
  },
  {
    name: "Atriox",
    species: "Jiralhanae (Brute)",
    faction: "banished",
    affiliation: "The Banished (Leader)",
    role: "Warlord",
    status: "Active",
    equipment: "Chainbreaker (Gravity Mace), Power Armor",
    weapons: "Chainbreaker gravity mace, heavy weapons, Banished technology",
    abilities: "Exceptional strength even for a Brute, tactical genius, leadership, combat expertise",
    biography:
      "Once a slave soldier for the Covenant, Atriox rose to prominence by surviving missions that killed his brethren. Eventually, he rebelled against the Covenant and formed the Banished, a powerful mercenary organization. His tactical brilliance and ruthlessness have made the Banished one of the greatest threats to humanity after the fall of the Covenant.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/halo-infinite-atriox-10-mp8W9p9EgVswj67p.jpg",
    firstAppearance: "Halo Wars 2 (2017)",
    threatLevel: 9,
    combatSkill: 9,
    intelligence: 9,
    leadership: 10,
    strength: 10,
    durability: 8,
    technology: 7,
  },
  {
    name: "Didact",
    species: "Forerunner (Promethean)",
    faction: "forerunner",
    affiliation: "Forerunner Ecumene",
    role: "Supreme Commander",
    status: "Contained (Composed)",
    equipment: "Forerunner Combat Skin, Constraint Fields",
    weapons: "Constraint fields, advanced Forerunner technology, Composer",
    abilities: "Telekinesis, near-immortality, superhuman strength and durability, advanced technological manipulation",
    biography:
      "The Didact was the supreme commander of the Forerunner military and husband to the Librarian. After being imprisoned for 100,000 years, he was accidentally released by the Master Chief and sought to use the Composer to transform humanity into Promethean Knights, viewing them as a threat to the galaxy.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/thumb-YNqBrjyG5bcQVqak.jpg",
    firstAppearance: "Halo 4 (2012)",
    threatLevel: 10,
    combatSkill: 10,
    intelligence: 10,
    leadership: 10,
    strength: 9,
    durability: 9,
    technology: 10,
  },
  {
    name: "The Weapon",
    species: "AI (Smart)",
    faction: "unsc",
    affiliation: "UNSC",
    role: "Cortana Countermeasure, Chief's Companion",
    status: "Active",
    equipment: "Data Network Access",
    weapons: "Hacking, system infiltration",
    abilities: "Advanced data analysis, hacking, tactical support, limited system control",
    biography:
      "Created by Dr. Catherine Halsey as a copy of Cortana designed to lock down and delete her rampant predecessor, the Weapon is a younger, more innocent AI who assists Master Chief during the conflict with the Banished on Zeta Halo. Unlike Cortana, she was designed with a deletion timer to prevent rampancy.",
    imageUrl: "https://assets.zyrosite.com/AR0L4M83e0TJRLvP/halo-infinite-weapon-cortana-story-spoilers-mP4OQE2n0lib6Nlz.jpeg",
    firstAppearance: "Halo Infinite (2021)",
    threatLevel: 7,
    combatSkill: 1,
    intelligence: 9,
    leadership: 5,
    strength: 1,
    durability: 6,
    technology: 9,
  },
]
